version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: queue_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: queue
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Если есть файл инициализации, можно добавить:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql\

volumes:
  postgres_data: